name: Update Podcast Episodes

on:
  # Shmiras Halashon - 3x per week (Mon/Wed/Fri at 6 AM UTC)
  schedule:
    - cron: '0 6 * * 1,3,5'  # Mon/Wed/Fri for Shmiras Halashon
    - cron: '0 7 * * 0'      # Sunday for Mesilas Yesharim  
    - cron: '0 6 * * 2'      # Tuesday for Shabbos Malkesa
    - cron: '0 8 1,15 * *'   # 1st and 15th for Hebrew Shmiras Einayim (bimonthly)
    - cron: '0 9 1 * *'      # 1st of month for other podcasts
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      podcast_filter:
        description: 'Which podcasts to check (comma-separated or "all")'
        required: false
        default: 'all'

jobs:
  update-episodes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Update episodes
      run: node scripts/update-episodes.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PODCAST_FILTER: ${{ github.event.inputs.podcast_filter || 'auto' }}
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are changes
        if [[ -n $(git status --porcelain) ]]; then
          git add data/episodes.json
          git commit -m "🎧 Auto-update podcast episodes [skip ci]"
          git push
          echo "✅ Episodes updated and pushed to repository"
        else
          echo "ℹ️ No new episodes found"
        fi