name: Update Podcast Episodes

on:
  schedule:
    # Run daily at 12:00 PM Israel Time (9:00 AM UTC)
    # This accounts for DST (UTC+3) - will be 11:00 AM IST during standard time (UTC+2)
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      podcast_filter:
        description: 'Which podcasts to update (comma-separated, or "all" for all)'
        required: false
        default: 'auto'
        type: string

jobs:
  update-episodes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Fetch full history to ensure we can detect changes
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Clean node_modules modifications
      run: |
        git checkout HEAD -- node_modules/ 2>/dev/null || true
        git clean -fd node_modules/ 2>/dev/null || true

    - name: Create data directory
      run: mkdir -p data

    - name: Update podcast episodes
      run: |
        if [ "${{ github.event.inputs.podcast_filter }}" != "" ]; then
          PODCAST_FILTER="${{ github.event.inputs.podcast_filter }}" npm run update-episodes
        else
          npm run update-episodes
        fi
      env:
        PODCAST_FILTER: ${{ github.event.inputs.podcast_filter || 'auto' }}

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -f data/episodes.json ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Files changed:"
          git status --porcelain
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No episodes.json file created"
        fi

    - name: Create summary
      run: |
        echo "## 🎧 Podcast Update Summary" > update_summary.md
        echo "" >> update_summary.md
        echo "**Status:** $(if [ "${{ steps.verify-changed-files.outputs.changed }}" = "true" ]; then echo "✅ Episodes updated"; else echo "ℹ️ No new episodes found"; fi)" >> update_summary.md
        echo "**Time:** $(date -u '+%Y-%m-%d %H:%M UTC')" >> update_summary.md
        echo "**Trigger:** ${{ github.event_name }}" >> update_summary.md
        echo "**Filter:** ${{ env.PODCAST_FILTER || 'auto' }}" >> update_summary.md
        echo "" >> update_summary.md
        echo "### 📊 Details:" >> update_summary.md
        if [ "${{ steps.verify-changed-files.outputs.changed }}" = "true" ]; then
          echo "- ✅ New episodes were found and processed" >> update_summary.md
          echo "- ✅ Changes committed to repository" >> update_summary.md
          echo "- ✅ Netlify rebuild triggered (if configured)" >> update_summary.md
        else
          echo "- ℹ️ All podcasts are up to date" >> update_summary.md
          echo "- ℹ️ No new episodes found" >> update_summary.md
        fi
        echo "" >> update_summary.md
        echo "---" >> update_summary.md
        echo "*Generated by GitHub Actions*" >> update_summary.md

    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        echo "📝 Attempting to commit changes..."

        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Check if there are actual changes to commit
        if git diff --quiet data/episodes.json; then
          echo "ℹ️ No changes detected in episodes.json - nothing to commit"
          exit 0
        fi

        # Add and commit changes
        git add data/episodes.json
        git commit -m "🔄 Auto-update podcast episodes

        Updated at: $(date -u '+%Y-%m-%d %H:%M UTC')
        Trigger: ${{ github.event_name }}
        Filter: ${{ env.PODCAST_FILTER || 'auto' }}"

        # Push changes
        echo "🚀 Pushing changes to repository..."
        git push origin main

        echo "✅ Changes committed and pushed successfully!"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger Netlify build
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        echo "Checking for Netlify build hook..."
        if [ -n "${{ secrets.NETLIFY_BUILD_HOOK }}" ]; then
          echo "Found Netlify build hook, triggering rebuild..."
          curl -X POST -d {} "${{ secrets.NETLIFY_BUILD_HOOK }}"
          echo "✅ Netlify build triggered successfully"
        else
          echo "⚠️ NETLIFY_BUILD_HOOK secret not configured"
          echo "⚠️ Site will not rebuild automatically"
          echo "⚠️ Manual rebuild required at Netlify dashboard"
        fi
